{% set version = "0.6.3" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}

{% set platform = "win_amd64" %}  # [win]
{% set platform = "manylinux1_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]

{% set fn = "{}-{}-{}-{}m-{}.whl".format("itk_meshtopolydata", version, pyver, pyver, platform) %}

package:
  name: itk-meshtopolydata
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ pyver }}/i/itk_meshtopolydata/{{ fn }}
  sha256: 4282d0f10a7b9ce976286fd5fdd4750c6997ec3e89e151152f67f3aae1532c7f  # [osx and py==36]
  sha256: 68f3fc721e801ab49027c30c9c4761513b69105f5b0d609cde2237cd87178369  # [osx and py==37]
  sha256: dd7a3bf1134b215a82810570bdb7dc0155ab1652f564d3f40c000ef2c7e8422c  # [osx and py==38]
  sha256: 3e7c5c17bd3c3518f03fde874dd2d0540e3c36aaef3f9ad0d004a7e373b2988c  # [osx and py==39]

  sha256: 07d3587a3bde862a0f0900be79d54c97ad4fb1b93920ab76c5dc2bbb5fc31d74  # [linux and py==36]
  sha256: 7a1ca27aea1d7f43524bd22ce1cbb897ecb44b8cb2e4bfdf052a71494a59b531  # [linux and py==37]
  sha256: 90218cbc28deadbd8428f86bffc503048571b97f4e3e2a364d7bf35f95de2895  # [linux and py==38]
  sha256: 3bfad563e9fc50f18702831bb123027e1bf821f3765f5be9045b37539a29c826  # [linux and py==39]

  sha256: dcf81d704df936a0cb7170caa46ddb5960e293261ad42bd05ceb1c1e65f8593e  # [win and py==36]
  sha256: 6596917170d75302c4bc0614bb34683972267dee8ee567166419445e291efed9  # [win and py==37]
  sha256: d7db6bcd22c8fa4a86500628aaf4fc0d10aa3907d0cd214c393853b7200e7d6d  # [win and py==38]
  sha256: fb9661e6618c294388d3648e2cd9d283d8e9de26455a743659854f2ed2ff08ee  # [win and py==39]

build:
  number: 1
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - itk >=5.1.2
    - numpy

test:
  imports:
    - itk

about:
  home: http://github.com/InsightSoftwareConsortium/ITKMeshToPolyData
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Convert an ITK Mesh to a simple data structure compatible with vtk.js PolyData'

  description: |
    ITK is an open-source, cross-platform library that provides developers
    with an extensive suite of software tools for image analysis. This package
    supports conversion of an itk.Mesh to a data structure compatible with
    vtk.js PolyData. It is used by the itk-jupyter-widgets (the itkwidgets package).

extra:
  recipe-maintainers:
    - thewtex
