{% set version = "0.6.2" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}

{% set platform = "win_amd64" %}  # [win]
{% set platform = "manylinux1_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]

{% set fn = "{}-{}-{}-{}m-{}.whl".format("itk_meshtopolydata", version, pyver, pyver, platform) %}

package:
  name: itk-meshtopolydata
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ pyver }}/i/itk_meshtopolydata/{{ fn }}
  sha256: 1b4aa1c0ead751e4eb8da7432118023e34fee7ecb93f1d9e95b880b8118288a0  # [osx and py36]
  sha256: 434dadab2008a6252194515ad78f4e67a7c5696bd534b5d776d7c38d4fe38b58  # [osx and py37]
  sha256: 43b66788607dd55f42912dc3db60f7feece7e3a1291fefe9c390b2eb7a3703bd  # [osx and py38]

  sha256: e1599f3fe268cd9afad9ea6cd41c946d7f6f26e92196c899a2d8d464e5bf81b7  # [linux and py36]
  sha256: b725a86b13bc642f0a6e35e0e5ffbbba45d5f158a00eb3fc7eceac7bcf24d75f  # [linux and py37]
  sha256: 486e418808c27ccc76619737219fa57fcd1de2da5fcd0325ee8c4395965deb39  # [linux and py38]

  sha256: 66859c1fac966398bac0bd928ff209d33f6f6f50bfc66a3771a783cac7be0690  # [win and py36]
  sha256: 0a3114861a10101bbb73a33642ee9322d569cd3c3a09803484c6b43a2fd1680f  # [win and py37]
  sha256: 82e5ee37382ad7291914444f07039cf72564d5ed76a0c987d0c3e0be9ade19ca  # [win and py38]

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - itk >=5.1.0
    - numpy

test:
  imports:
    - itk

about:
  home: http://github.com/InsightSoftwareConsortium/ITKMeshToPolyData
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Convert an ITK Mesh to a simple data structure compatible with vtk.js PolyData'

  description: |
    ITK is an open-source, cross-platform library that provides developers
    with an extensive suite of software tools for image analysis. This package
    supports conversion of an itk.Mesh to a data structure compatible with
    vtk.js PolyData. It is used by the itk-jupyter-widgets (the itkwidgets package).

extra:
  recipe-maintainers:
    - thewtex
