{% set version = "0.6.0" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}

{% set platform = "win_amd64" %}  # [win]
{% set platform = "manylinux1_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]

{% set fn = "{}-{}-{}-{}m-{}.whl".format("itk_meshtopolydata", version, pyver, pyver, platform) %}

package:
  name: itk-meshtopolydata
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ pyver }}/i/itk_meshtopolydata/{{ fn }}
  sha256: af9aaea8ca845b8a194803bd92a517580ccc08c97a5acc096048328a8dfcf489  # [osx and py36]
  sha256: 3765c147f8422f35fee1fb18ed5a6c6ade810a7fd6041f2b927aed635515b14c  # [osx and py37]
  sha256: cca08c4cc2f0a3aad19f54dd073eb4cdf10e66523692b54d2c69335107a68a3b  # [osx and py38]

  sha256: fad1c7135af2c36c85c2afdf353c1fbaab99ae1629f108d185283d63def03aea  # [linux and py36]
  sha256: f82969f3176e45de38940f9549644f5acd45c27c31eefe81df3065cf60ad3f15  # [linux and py37]
  sha256: 302a433c3da28a98fe33c55ebeb5da93a9ef95e5f0cf9d784551a7647d573af4  # [linux and py38]

  sha256: 6fc084faa43d1409633d41d3d7a8e13ed6dae558928f4c9b3238f69fc173735e  # [win and py36]
  sha256: 728513695fa7d6c48b6bb508069f0542a8a3e6237436fd094a614c7a67b1148d  # [win and py37]
  sha256: 2664b665a5a662a7413c4d6c1e925464277107a529fc3eff605a98d1cbe2aa22  # [win and py38]

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - itk >=5.1.0
    - numpy

test:
  imports:
    - itk

about:
  home: http://github.com/InsightSoftwareConsortium/ITKMeshToPolyData
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Convert an ITK Mesh to a simple data structure compatible with vtk.js PolyData'

  description: |
    ITK is an open-source, cross-platform library that provides developers
    with an extensive suite of software tools for image analysis. This package
    supports conversion of an itk.Mesh to a data structure compatible with
    vtk.js PolyData. It is used by the itk-jupyter-widgets (the itkwidgets package).

extra:
  recipe-maintainers:
    - thewtex
