travis:
  secure:
    BINSTAR_TOKEN: R1E1bsLEZWWADy3GlnkXD6EF90jDASAEREmRvdYWRbrM00+MmguZyEgTFeTUJ2CzX1dOBAh3bfU0G6XY/4jtNXdlhDfH+K3VovQVv6sdbUQWBA0Hiqb6lI2/dhrE3/O4tgkgThPo6T0n4qFxuouhvJmhreT+gaZq1/Yes0G+k6WbvxE80lJ80NmwQzvf3j76JIisGw9g6QkEgeDW3JEJab7IdehoOIMX4JCe3+hm7t7euM7pyhOryuPAjO26LBHAnHMe7X52LSULSsEnJtCcHJw/n8/WP13DOe/HmNU2XWRMpnDivkqHgLls6t/DUomk6VJVpY1C3ikYEbLnYUySxfVDgnqusk2JH/nnUnY+5e9+ib7kebLVfqwTsyPShkqiPoeAZmAXG1zc7/d9dmT1PyziDXE1/BJARs4LTakdAKp3kUXexul2dAleut4kfvZtU7sQ56D5nIbYXc4kgO3O7WY4PN8D7FltEiIN4XUxBaBDN4vrat3LzWWeQ7eBz5ExD1FfLNNomMCMorQLj+UFBitEQVO8CxZlbiWboIJvJ4iCJubB4+mkgd/FKPIc3A9PjzB4LarHoxNVtnbmiAsVOxcKt++xcKqkhDAS71RGt06t4TpSOv1rKX7uHOGsSvJKuIUdSu3jxkm6fJB9uWxy0bcZBogv5xhocZWr2YlUvLU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
